version: "3"
services:
  signaling:
    build:
      context: ./packages/signaling
    ports:
      - 3000:3000
    volumes:
      - ./packages/signaling/conf:/app/config
  turn:
    image: coturn/coturn:latest
    network_mode: host
    command: -n --min-port=49160 --max-port=49200 -u admin:credential --lt-cred-mech
    tty: true
    stdin_open: true
