name: Release grabber

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install agent dependencies
        working-directory: ./packages/grabber
        run: npm ci

      - name: Run agent build
        working-directory: .
        run: bash ./grabber_build.sh linux x64
      - name: Create tar archive
        working-directory: ./packages/grabber/build/
        run: tar -czvf ./../webrtc_grabber_agent_linux_x64.tar.gz .
      - uses: actions/upload-artifact@v4
        with:
          name: webrtc_agent_grabber_linux_x64.tar.gz
          path: ./packages/grabber/webrtc_grabber_agent_linux_x64.tar.gz
          retention-days: 7

  build_windows:
    runs-on: windows-2019
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install agent dependencies
        working-directory: .\packages\grabber
        run: npm ci

      - name: Run agent build
        working-directory: .
        shell: cmd
        run: |
          grabber_build_win64.bat

      - uses: actions/upload-artifact@v4
        with:
          name: webrtc_grabber_agent_win_x64
          path: ./packages/grabber/build/
          retention-days: 7
#      - name: Assemble with Gradle
#        env:
#          CHROME_BIN: C:\soft\GoogleChromePortable\GoogleChromePortable.exe
#        run: .\gradlew.bat assemble
#      - name: Warm up js browser
#        shell: cmd
#        env:
#          CHROME_BIN: C:\soft\GoogleChromePortable\GoogleChromePortable.exe
#        run: gradlew.bat jsBrowserTest || exit 0
#      - name: Test with Gradle
#        env:
#          CHROME_BIN: C:\soft\GoogleChromePortable\GoogleChromePortable.exe
#        run: .\gradlew.bat check
#      - name: Upload check reports
#        uses: actions/upload-artifact@v3
#        if: always()
#        with:
#          name: build-reports-win
#          path: build/reports/
#          retention-days: 1
